### ISSUE TITLE
add_objects not working?

### ISSUE THREAD

**Issue by jgrn307** [SESYNC-ci/rslurm#25] opened 2018-01-25 20:52 UTC
Folks, I am trying to run a job that adds non-looping objects via the add_objects, but the workers don't appear to be "seeing" the objects (I've confirmed they aren't being assigned to the function).  I noticed that the line:

.rslurm_result <- do.call(parallel::mcmapply, c(
    FUN = .rslurm_func,
    .rslurm_params[.rslurm_istart:.rslurm_iend, , drop = FALSE],
    mc.cores = {{{cpus_per_node}}},
    SIMPLIFY = FALSE))

Doesn't have a MoreArgs (?mcmapply) which I would think would be needed for the functions to receive the additional parameters.  Can you confirm/fix?  Thanks!

**Comment by pmarchand1** [comment] 2018-01-25 21:00
There's a line earlier that loads the content of the .RData file into the R session.

load('add_objects.RData')

Note how add_objects are specified in the function documentation, specifically, the names of the objects need to be passed as strings:

>  add_objects: A character vector containing the name of R objects to be saved in a .RData file and loaded on each cluster node prior to calling _f_.

**Comment by jgrn307** [comment] 2018-01-25 22:37
I'm not convinced this is working.  I tried a very simply modification of your test script, modifying your "ftest" to simply include a "moo" parameter that should print:

pars <- data.frame(par_m = seq(-10, 10, length.out = 1000), 
		par_sd = seq(0.1, 10, length.out = 1000))

moo <- "Passing along args!"

ftest <- function(par_m, par_sd, moo) {
	print(moo)
	samp <- rnorm(10^7, par_m, par_sd)
	c(s_m = mean(samp), s_sd = sd(samp))
}

sjob1 <- slurm_apply(ftest, pars, add_objects=c("moo"))


Once I submit this to the queue, I'm getting an immediate failure of the job, and the slurm_0 gives me:

Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code

Note that your original function without the "moo" it works as expected.

Am I doing something wrong?  Or can you confirm this isn't working on your end?

**Comment by jgrn307** [comment] 2018-01-25 22:45
One more test, if I modify the function to explicitly load the object file, it works fine, so something is going on where the objects from the .Rdata file are not being passed to the function properly:

ftest <- function(par_m, par_sd, moo) {
	load("~/_rslurm_testrslurm02/add_objects.RData")
	print(moo)
	samp <- rnorm(10^7, par_m, par_sd)
	c(s_m = mean(samp), s_sd = sd(samp))
}

**Comment by pmarchand1** [comment] 2018-01-25 23:22
Ok, the issue is that "add_objects" is not meant to serve as "MoreArgs". It is there to store objects from the current R session (global environment) that need to be loaded on the cluster. So for example, if you remove "moo" from the parameter list in ftest and you keep "print(moo)" inside the function, it should work.

If, say, you were using a pre-made function that needed moo as a parameter, either you repeat the value of moo in your data frame so all parameters are vectorized, or you could use a wrapper function that only has looping parameters. (See example in the vignette under "Adding auxiliary data and functions".)

We could add a "MoreArgs" argument to slurm_apply (which would receive a named list), save it as a .RDS (as the parameters and function objects currently are) and load it on the cluster to pass to mcmapply. It seems it should work, but we should still build tests to make sure.

**Comment by jgrn307** [comment] 2018-01-25 23:28
Ok, this helps a lot!  I'd like to make the case for using it as a MoreArgs so it can be easier to port to other parallel systems and debug properly.  I always get a little leery of functions that reference variables defined in their parent environment without being an explicit parameter.  Thanks for explaining this tho, I'd never have thought of removing the stuff from the parameters!

**Comment by itcarroll** [comment] 2018-01-26 14:25
Can you point me to an example of "other parallel systems" that use MoreArgs the way you are recommending implementation in rslurm? Thanks!

**Comment by jgrn307** [comment] 2018-01-26 17:11
mcmapply, of course, has the "MoreArgs".  foreach has ".export" (which, like your code, asks for a character vector of variables for export).  And there is the debugging concept -- if I'm trying to debug a function that requires those variables to be in the global environment that makes life a bit more difficult (and potentially dangerous) vs. just passing the key parameters to the function in a non-rslurm/parallel way.

**Comment by qdread** [comment] 2020-01-14 20:28
I've created a branch that implements this idea in slurm_apply() as well as in a new function called slurm_map() that is analogous to lapply() or map(). https://github.com/SESYNC-ci/rslurm/tree/slurmmaptest  @pmarchand1 I think it works fine but haven't built the tests yet to confirm it works. I haven't yet taken your suggestion to rename add_objects but I can also do that. Once it passes all the tests I can merge it with the master branch.

**Comment by qdread** [comment] 2020-01-31 18:33
The updates in the most recent commit #48 address this issue, closing!

**Closed by qdread** 2020-01-31 18:33 UTC
